modified bin

diff --git a/.local/bin/ubuntustyle b/.local/bin/ubuntustyle
--- a/.local/bin/ubuntustyle
+++ b/.local/bin/ubuntustyle
@@ -2,25 +2,25 @@
 
 # anshul333y's ubuntustyle script
 
-WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
+WALLPAPER_DIR="$HOME/Pictures/wall"
 
 # Use argument as wallpaper if provided, otherwise pick a random one
 if [ -n "$1" ]; then
-    WALLPAPER="$1"
+  WALLPAPER="$1"
 else
-    WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf -n 1)
+  WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf -n 1)
 fi
 
 # Check if the wallpaper file exists
 if [ ! -f "$WALLPAPER" ]; then
-    echo "Wallpaper not found: $WALLPAPER"
-    exit 1
+  echo "Wallpaper not found: $WALLPAPER"
+  exit 1
 fi
 
 # Pywal
 wal -i "$WALLPAPER" || {
-    echo "pywal failed"
-    exit 1
+  echo "pywal failed"
+  exit 1
 }
 
 gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER"
